<?php
/**
 * @package	gutenberg-incompatibility-status
 * @author	Ingo Steinke
 * @version 1.0.0
 *
 * @wordpress-plugin
 * Plugin Name: Gutenberg Incompatibility Status
 * Text Domain: gutenberg-incompatibility-status
 * Domain Path: /languages
 * Plugin URI: https://github.com/openmindculture/wp-incompatibility-status/
 * Description: Gutenberg Incompatibility Status adds a status message to the admin dashboard to display possible incompatibility issues using the block editor and full-site editing.
 * Short Description: Show Gutenberg Incompatibility Status in WP-Admin
 * Version: 1.0.0
 *  Author: openmindculture
 * Author URI: https://wordpress.org/support/users/openmindculture/
 * Requires at least: 6.0
 * Tested up to: 6.3
 * Requires PHP: 7.4
 */

if ( is_admin() ) {
	define( 'openmindculture_gutenbergstatus__PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
	define( 'openmindculture_gutenbergstatus__PLUGIN_VERSION', '1.0.0');



	function openmindculture_gutenbergstatus__dashboard_widgets() {
		global $wp_meta_boxes;

		wp_add_dashboard_widget('custom_help_widget', 'Gutenberg Incompatibility Warnings', 'openmindculture_gutenbergstatus__content');
	}

	function openmindculture_gutenbergstatus__content() {
		$details = [];
		$warnings = 0;
		global $wp_version;



		if ($wp_version)
		{
			array_push($details, "WordPress version: $wp_version");
		}

		if (phpversion())
		{
			array_push($details, 'PHP version: ' . phpversion());
		}
		// Gutenberg (via plugin) version, if any
		// site builders or custom editor plugins by known slug name
		// site builders or custom editor plugins by tag names
		// active theme capabilities by tag names

		$plugin_entrypoint = WP_PLUGIN_DIR . '/woocommerce/woocommerce.php';
		$plugin_data = get_plugin_data($plugin_entrypoint);
		$woocommerce_version = $plugin_data['Version'];
		if ($woocommerce_version) {
			array_push($details, "WooCommerce version: $woocommerce_version");
		}

		openmindculture_gutenbergstatus__print_styles();

		if ($warnings > 1)
		{
			echo<<<EOT
<p class="openmindculture_gutenbergstatus__summary openmindculture_gutenbergstatus__summary--warning">$warnings issues might need your attention.</p>
EOT;
		}
		else if ($warnings > 0)
		{
			echo<<<EOT
<p class="openmindculture_gutenbergstatus__summary openmindculture_gutenbergstatus__summary--warning">One issue might need your attention.</p>
EOT;
		}
		else
		{
			echo<<<EOT
<p class="openmindculture_gutenbergstatus__summary openmindculture_gutenbergstatus__summary--ok">No critical issues detected.</p>
EOT;
		}

		echo '<ul>';
		foreach ($details as $i => $value) {
			echo "<li>$value</li>";
		}
		echo '</ul>';

		echo '<p>This message is generated by the <b>Gutenberg Incompatibility Status</b> plugin currently active on this site. You can disable the plugin on the <a href="plugins.php">plugins page</a>.</p>';
	}

	function openmindculture_gutenbergstatus__print_styles() {
		?>
		<style>
			.openmindculture_gutenbergstatus__summary {
				font-size: 16px;
			}
			.openmindculture_gutenbergstatus__summary::after {
				width: 12px;
				height: 12px;
				margin-left: 8px;
				margin-bottom: -8px;
			}
			.openmindculture_gutenbergstatus__summary--ok::after {
				content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 64 64' enable-background='new 0 0 64 64'%3E%3Cpath d='M32,2C15.431,2,2,15.432,2,32c0,16.568,13.432,30,30,30c16.568,0,30-13.432,30-30C62,15.432,48.568,2,32,2z M25.025,50 l-0.02-0.02L24.988,50L11,35.6l7.029-7.164l6.977,7.184l21-21.619L53,21.199L25.025,50z' fill='%2343a047'/%3E%3C/svg%3E");
			}
			.openmindculture_gutenbergstatus__summary--warning::after {
				content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 20 20'%3E%3Ctitle%3E alert %3C/title%3E%3Cstyle type='text/css'%3E* %7B fill: %23fc3 %7D%3C/style%3E%3Cpath d='M19.64 16.36L11.53 2.3A1.85 1.85 0 0 0 10 1.21 1.85 1.85 0 0 0 8.48 2.3L.36 16.36C-.48 17.81.21 19 1.88 19h16.24c1.67 0 2.36-1.19 1.52-2.64zM11 16H9v-2h2zm0-4H9V6h2z'/%3E%3C/svg%3E");
			}
		</style>
		<?php
	}

	add_action('wp_dashboard_setup', 'openmindculture_gutenbergstatus__dashboard_widgets');
}
