<?php
/**
 * @package	gutenberg-incompatibility-status
 * @author	Ingo Steinke
 * @version 1.0.0
 *
 * @wordpress-plugin
 * Plugin Name: Gutenberg Incompatibility Status
 * Text Domain: gutenberg-incompatibility-status
 * Domain Path: /languages
 * Plugin URI: https://github.com/openmindculture/wp-incompatibility-status/
 * Description: Gutenberg Incompatibility Status adds a status message to the admin dashboard to display possible incompatibility issues using the block editor and full-site editing.
 * Short Description: Show Gutenberg Incompatibility Status in WP-Admin
 * Version: 1.0.0
 *  Author: openmindculture
 * Author URI: https://wordpress.org/support/users/openmindculture/
 * Requires at least: 6.0
 * Tested up to: 6.3
 * Requires PHP: 7.4
 */

if ( is_admin() ) {
	define( 'openmindculture_gutenbergstatus__PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
	define( 'openmindculture_gutenbergstatus__PLUGIN_VERSION', '1.0.0');



	function openmindculture_gutenbergstatus__dashboard_widgets() {
		global $wp_meta_boxes;

		wp_add_dashboard_widget('custom_help_widget', 'Gutenberg Incompatibility Warnings', 'openmindculture_gutenbergstatus__content');
	}

	function openmindculture_gutenbergstatus__content() {
		$details = [];
		$warnings = 0;
		global $wp_version;

		if ($wp_version)
		{
			array_push($details, "WordPress version: $wp_version");
		}

		if (phpversion())
		{
			array_push($details, 'PHP version: ' . phpversion());
		}
		// Gutenberg (via plugin) version, if any
		// site builders or custom editor plugins by known slug name
		// site builders or custom editor plugins by tag names
		// active theme capabilities by tag names

		if ($warnings > 0)
		{
			echo "<p class=warn>$warnings issues might need your attention.</p>";
		}
		else
		{
			echo '<p class=ok>No critical issues detected.</p>';
		}

		echo '<ul>';
		foreach ($details as $i => $value) {
			echo "<li>$value</li>";
		}
		echo '</ul>';

		echo '<p>This message is generated by the <b>Gutenberg Incompatibility Status</b> plugin currently active on this site. You can disable the plugin on the <a href="plugins.php">plugins page</a>.</p>';
	}

	add_action('wp_dashboard_setup', 'openmindculture_gutenbergstatus__dashboard_widgets');
}
